Set up clang-format and pre-commit hooks
hpvb/ppelib pull request #4
Opened 2021-03-03 00:11 UTC by Calinou

I tried to make `.clang-format` suit the current coding style as much as possible, but feel free to suggest tweaks anyway.

See https://pre-commit.com for more information.

2021-03-03 13:21 UTC, hpvb requested changes
I am happy with the idea and the framework proposed but I don't think I like the actual .clang-format in here. Could you make a PR with the same but without the file changes and an empty clang format ruleset? I think changing the clang-format file while discussing on a PR is going to be very cumbersome for the both of us.

2021-03-03 13:21 UTC, hpvb commented on src/thread_local.h
> +#if __STDC_VERSION__ >= 201112 && !defined __STDC_NO_THREADS__
Not sure I like what happened here.

2021-03-03 13:21 UTC, hpvb commented on include/ppelib/ppelib-low-level.h
> -ppelib_header_t* ppelib_get_header(ppelib_handle *handle);
I personally prefer my pointers on the type as it's part of the type.

2021-03-03 17:16 UTC, Calinou commented
@hpvb Done. I rebased this PR against the `main` branch as well.

2021-03-03 17:41 UTC, hpvb approved these changes

2021-03-03 17:41 UTC, merged

2021-03-03 17:41 UTC, hpvb commented
Thanks!

2021-03-08 02:04 UTC, hpvb commented
I found it easier to just integrate clang-format with eclipse and deal with the differences. I ended up merging your exact `.clang-format` into the refactor2 branch which should become main soon.